apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-ns
  labels:
    name: hello-world-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap
  namespace: hello-world-ns
data:
  HELLO_WORLD_CONFIG_VAR: hello-world-from-config-map-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: hello-world-configmap
      containers:
        - name: hello-world
          image: hello-world-sam
          imagePullPolicy: Never
          env:
            # Define the environment variable
            - name: HELLO_WORLD_CONFIG_VAR # Notice that the case is different here
                                        # from the key name in the ConfigMap.
              valueFrom:
                configMapKeyRef:
                  name: hello-world-configmap           # The ConfigMap this value comes from.
                  key: HELLO_WORLD_CONFIG_VAR # The key to fetch.
---
apiVersion: v1
kind: Service
metadata:
   name: hello-world-entrypoint
   namespace: hello-world-ns
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001