apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-ns
  labels:
    name: hello-world-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap
data:
  MESSAGE_KEY: hello-world-from-config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: hello-world-configmap
      containers:
        - name: hello-world
          image: hello-world-sam
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: ./src/app.ts
---
apiVersion: v1
kind: Service
metadata:
   name: hello-world-entrypoint
   namespace: hello-world-ns
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001